# Generated by Django 4.2.28 on 2026-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rent_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['end_date'], name='pms_lease_end_dat_225ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='pms_payment_date_233ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['rent_due_date'], name='pms_tenant_rent_du_d20daf_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status'], name='pms_unit_status_0f36a0_idx'),
        ),
    ]
